name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tasqiai-api
  AZURE_WEBAPP_PACKAGE_PATH: server/publish
  DOTNET_VERSION: '6.0.x'
  WORKING_DIRECTORY: server

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          dotnet publish -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

  deploy:
    permissions:
      id-token: write
      contents: read
      actions: write
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          use-oidc: true
          audience: api://AzureADTokenExchange
          subject-name: repo:bryancris/tasqiai:ref:refs/heads/main
          allow-no-subscriptions: false

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
