name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tasqiai-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: dotnet build and publish
      run: |
        cd server
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

    - name: Install EF Tool
      run: |
        cd server
        dotnet new tool-manifest
        dotnet tool install dotnet-ef

    - name: Generate Migration Script
      run: |
        cd server
        dotnet ef migrations script --idempotent --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/migrate.sql

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Apply Database Migrations
      uses: azure/sql-action@v2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION }}
        path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/migrate.sql

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
